export const insightsData = {
  tabs: [
    { id: "overview", label: "Overview" },
    { id: "money-in", label: "Money in" },
    { id: "money-out", label: "Money out" },
  ],
  months: ["May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun"],
  metrics: [
    { label: "Net cashflow", value: "$999,201", featured: true },
    { label: "Money in", value: "$1.9M" },
    { label: "Money out", value: "-$910,264" },
  ],
  rangeWindows: [
    {
      id: "early",
      label: "Feb 14 - Mar 31",
      buttonLabel: "Feb 14-Mar 31",
      left: 52,
      width: 20,
      summary: {
        net: "-$118,420",
        moneyIn: "$612,840",
        moneyOut: "-$731,260",
        topSource: "Google",
        customerReceipts: "$318K",
        topRecipient: "GUSTO",
        cardSpend: "-$141K",
      },
    },
    {
      id: "spring",
      label: "Mar 10 - Apr 30",
      buttonLabel: "Mar 10-Apr 30",
      left: 62,
      width: 22,
      summary: {
        net: "$342,918",
        moneyIn: "$1.2M",
        moneyOut: "-$857,082",
        topSource: "GenPro, Inc.",
        customerReceipts: "$462K",
        topRecipient: "Google",
        cardSpend: "-$226K",
      },
    },
    {
      id: "current",
      label: "Feb 14 - May 25",
      buttonLabel: "Feb 14-Today",
      left: 71,
      width: 25,
      summary: {
        net: "$999,201",
        moneyIn: "$1.9M",
        moneyOut: "-$910,264",
        topSource: "Venture Debt Loan",
        customerReceipts: "$605K",
        topRecipient: "GUSTO",
        cardSpend: "-$303K",
      },
    },
  ],
  trendNotes: [
    {
      title: "Runway and cash position",
      body:
        "Net cash flow is -$2,970.23 YTD. Your Mercury balances total $334.5K with a monthly burn rate of -$45.2K/mo. Runway setting: last 3 fully completed months.",
      tone: "blue",
    },
    {
      title: "Money out trends",
      body:
        "Spending was -$303K across 182 transactions. In the prior period, it was $33.4K across 226 transactions, an increase of $269.6K.",
      tone: "rose",
    },
    {
      title: "Money in trends",
      body: "Money in reached $764,806 with GenPro contributing 54.2% and Google 14.6% of total inflows.",
      tone: "green",
    },
  ],
  moneyIn: {
    title: "Money in",
    total: "$1,909,466",
    groupLabel: "Group Money in by",
    options: ["Source", "Category", "GL Code"],
    rows: [
      ["Venture Debt Loan", "52.3%", "$1,000,000.00"],
      ["GenPro, Inc.", "21.7%", "$414,983.19"],
      ["Google", "6.1%", "$117,782.43"],
      ["Milgram Brokerage", "4.4%", "$84,710.74"],
      ["Orange, Inc.", "3.8%", "$73,021.73"],
      ["Check Deposit", "2.9%", "$55,810.16"],
      ["Monarch Books", "2.0%", "$38,850.99"],
      ["Remaining sources", "6.5%", "$124,306.65"],
    ],
  },
  moneyOut: {
    title: "Money out",
    total: "-$910,264",
    groupLabel: "Group Money out by",
    options: ["Recipient", "Category", "GL Code"],
    rows: [
      ["GUSTO", "29.5%", "-$268,986.75"],
      ["Google", "13.0%", "-$118,921.98"],
      ["Jordi O'Donnell", "9.9%", "-$90,797.16"],
      ["Milgram Brokerage", "9.7%", "-$89,061.60"],
      ["Orange, Inc.", "8.0%", "-$73,011.09"],
      ["Greenwich Capital", "6.9%", "-$63,218.83"],
      ["Molitor Ventures", "4.3%", "-$40,012.34"],
      ["Remaining recipients", "18.2%", "-$166,254.70"],
    ],
  },
};
