export const accountingTabs = [
  { id: "all", label: "All" },
  { id: "needs", label: "Needs review", badge: "999+" },
  { id: "ready", label: "Ready to Export" },
  { id: "sync", label: "Sync Error", badge: "3" },
  { id: "exported", label: "Exported" },
];

export const filterTabs = [
  ["Date", "calendar"],
  ["Keyword", "search"],
  ["Amount", "dollar"],
  ["Method", "card"],
  ["Category", "bookmark"],
  ["Merchant Type", "account"],
  ["GL Code", "table"],
  ["Account", "account"],
  ["Receipt", "receipt"],
  ["Status", "check"],
  ["Card", "card"],
  ["Policy", "settings"],
];

export const categoryOptions = [
  "Contractor Payments",
  "Business Client Meals",
  "Office Supplies",
  "Lunch Perks",
  "Venue Rental",
  "Employee Gifts",
  "Travel",
];

export const glCodeOptions = [
  "734 - COGS",
  "215 - Accounts Payable",
  "404 - Inactive GL Code",
  "318 - Unbilled Receivables",
  "610 - Meals & Entertainment",
  "711 - Office Expense",
];

export const accountingRows = [
  {
    id: "contractor",
    date: "May 25",
    name: "Contractor",
    amount: "-$213.11",
    method: "Mercury ACH Payment",
    methodIcon: "send",
    mark: "C",
    category: "Contractor Payments",
    glCode: "734 - COGS",
    status: "needs",
    note: "Add note",
  },
  {
    id: "working-capital",
    date: "May 25",
    name: "Mercury Working Capital",
    amount: "-$2,200.00",
    method: "Working Capital Loan Payment",
    methodIcon: "request",
    mark: "mark",
    category: "",
    glCode: "",
    status: "sync",
    note: "Working Capital loan payment",
  },
  {
    id: "acme",
    date: "May 25",
    name: "Payment from Acme Corp",
    amount: "$200.00",
    method: "Request or Invoice Payment",
    methodIcon: "transfer",
    mark: "P",
    category: "",
    glCode: "",
    status: "needs",
    note: "Add note",
  },
  {
    id: "lilys-small",
    date: "May 25",
    name: "Lily's Eatery",
    amount: "$0.93",
    method: "Alice C. ••1234",
    methodIcon: "card",
    mark: "LE",
    category: "",
    glCode: "",
    status: "needs",
    note: "Lunch with the team",
  },
  {
    id: "deli-mary",
    date: "May 25",
    name: "Deli 77",
    amount: "$63.53",
    method: "Mary M. ••0332",
    methodIcon: "card",
    mark: "D7",
    category: "Business Client Meals",
    glCode: "215 - Accounts Payable",
    status: "needs",
    note: "Add note",
  },
  {
    id: "deli-jane",
    date: "May 25",
    name: "Deli 77",
    amount: "$214.06",
    method: "Jane B. ••6112",
    methodIcon: "card",
    mark: "D7",
    category: "Business Client Meals",
    glCode: "215 - Accounts Payable",
    status: "needs",
    note: "Add note",
  },
  {
    id: "office-stop-a",
    date: "May 25",
    name: "Office Stop Co.",
    amount: "-$287.89",
    method: "Jessica A. ••9914",
    methodIcon: "card",
    mark: "OS",
    category: "Office Supplies",
    glCode: "",
    status: "sync",
    note: "Misc office supplies",
  },
  {
    id: "trader-johns-a",
    date: "May 25",
    name: "Trader John's",
    amount: "$855.81",
    method: "Landon S. ••0331",
    methodIcon: "card",
    mark: "TJ",
    tone: "red",
    category: "Lunch Perks",
    glCode: "215 - Accounts Payable",
    status: "needs",
    note: "Groceries for the office",
  },
  {
    id: "pending-deposit",
    date: "May 25",
    name: "Pending Deposit",
    amount: "$1,000.00",
    method: "Check Deposit",
    methodIcon: "deposit",
    mark: "PD",
    category: "",
    glCode: "404 - Inactive GL Code",
    status: "sync",
    note: "Pending deposit",
  },
  {
    id: "office-stop-b",
    date: "May 25",
    name: "Office Stop Co.",
    amount: "-$662.70",
    method: "Jane B. ••0330",
    methodIcon: "card",
    mark: "OS",
    category: "Office Supplies",
    glCode: "",
    status: "needs",
    note: "Misc office supplies",
  },
  {
    id: "office-stop-c",
    date: "May 25",
    name: "Office Stop Co.",
    amount: "$563.94",
    method: "Jane B. ••0330",
    methodIcon: "card",
    mark: "OS",
    category: "Office Supplies",
    glCode: "",
    status: "ready",
    note: "Misc office supplies",
  },
  {
    id: "plant-cafe",
    date: "May 25",
    name: "The Plant Organic Cafe",
    amount: "-$203.03",
    method: "Landon S. ••4929",
    methodIcon: "card",
    mark: "PO",
    category: "Business Client Meals",
    glCode: "",
    status: "exported",
    note: "Lunch with the team",
  },
  {
    id: "trader-johns-b",
    date: "May 25",
    name: "Trader John's",
    amount: "-$189.12",
    method: "Alice C. ••6231",
    methodIcon: "card",
    mark: "TJ",
    tone: "red",
    category: "Lunch Perks",
    glCode: "215 - Accounts Payable",
    status: "exported",
    note: "Groceries for the office",
  },
  {
    id: "milgram",
    date: "May 25",
    name: "Milgram Brokerage",
    amount: "$2,760.75",
    method: "Jane B. ••3745",
    methodIcon: "card",
    mark: "MB",
    category: "Venue Rental",
    glCode: "",
    status: "ready",
    note: "Brokerage partner",
  },
  {
    id: "monarch",
    date: "May 25",
    name: "Monarch Books",
    amount: "$423.13",
    method: "Alice C. ••7840",
    methodIcon: "card",
    mark: "MB",
    category: "Employee Gifts",
    glCode: "318 - Unbilled Receivables",
    status: "exported",
    note: "Books for the office",
  },
  {
    id: "lilys-jane",
    date: "May 25",
    name: "Lily's Eatery",
    amount: "$25.89",
    method: "Jane B. ••5555",
    methodIcon: "card",
    mark: "LE",
    category: "",
    glCode: "",
    status: "needs",
    note: "Lunch with the team",
  },
];
