export const expenseRequests = [
  {
    id: "exp-101",
    date: "May 25",
    submittedAt: "9:14 AM",
    member: "Maya Chen",
    role: "TD Banking",
    initials: "MC",
    status: "pending",
    amount: 482.4,
    merchant: "Cedar Room",
    memo: "Sponsor dinner with Alpine Capital",
    category: "Meals",
    receipt: "attached",
    policy: "inside",
    policyNote: "Within client entertainment limit",
    source: "Mobile receipt",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-102",
    date: "May 25",
    submittedAt: "8:03 AM",
    member: "Owen Patel",
    role: "Coverage",
    initials: "OP",
    status: "payment",
    amount: 63.18,
    merchant: "Amtrak",
    memo: "Northeast corridor client travel",
    category: "Travel",
    receipt: "attached",
    policy: "inside",
    policyNote: "Auto-approved travel class",
    source: "Corporate card sync",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-103",
    date: "May 24",
    submittedAt: "5:42 PM",
    member: "Jane Smith",
    role: "Analyst",
    initials: "JS",
    status: "details",
    amount: 129.0,
    merchant: "Figma",
    memo: "Prototype workspace seat",
    category: "Software",
    receipt: "missing",
    policy: "needs-review",
    policyNote: "Missing itemized receipt",
    source: "Manual upload",
    reviewer: "Finance queue",
  },
  {
    id: "exp-104",
    date: "May 24",
    submittedAt: "3:20 PM",
    member: "Lina Morales",
    role: "Origination",
    initials: "LM",
    status: "pending",
    amount: 812.77,
    merchant: "United Airlines",
    memo: "SFO investor roadshow",
    category: "Airfare",
    receipt: "attached",
    policy: "inside",
    policyNote: "Trip linked to active engagement",
    source: "Email receipt",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-105",
    date: "May 23",
    submittedAt: "11:51 AM",
    member: "Noah Brooks",
    role: "CRG",
    initials: "NB",
    status: "action",
    amount: 246.62,
    merchant: "Staples",
    memo: "Investor book print run",
    category: "Office",
    receipt: "attached",
    policy: "flagged",
    policyNote: "Vendor requires cost center confirmation",
    source: "Receipt inbox",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-106",
    date: "May 23",
    submittedAt: "10:18 AM",
    member: "Priya Shah",
    role: "Sponsor Coverage",
    initials: "PS",
    status: "declined",
    amount: 1296.5,
    merchant: "The Mercer",
    memo: "Two-night hotel stay",
    category: "Lodging",
    receipt: "attached",
    policy: "flagged",
    policyNote: "Rate exceeds policy by 18%",
    source: "Travel portal",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-107",
    date: "May 22",
    submittedAt: "4:44 PM",
    member: "Caleb Stone",
    role: "TD Banking",
    initials: "CS",
    status: "pending",
    amount: 38.7,
    merchant: "Uber",
    memo: "Client office transfer",
    category: "Ground",
    receipt: "attached",
    policy: "inside",
    policyNote: "Ride matched calendar location",
    source: "Corporate card sync",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-108",
    date: "May 22",
    submittedAt: "1:27 PM",
    member: "Amelia Wong",
    role: "Coverage",
    initials: "AW",
    status: "approved",
    amount: 87.44,
    merchant: "Blue Bottle",
    memo: "Breakfast prep with coverage team",
    category: "Meals",
    receipt: "attached",
    policy: "inside",
    policyNote: "Approved and batched",
    source: "Mobile receipt",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-109",
    date: "May 21",
    submittedAt: "2:10 PM",
    member: "Ethan Lee",
    role: "Analyst",
    initials: "EL",
    status: "pending",
    amount: 392.25,
    merchant: "Delta",
    memo: "Atlanta buyer meeting",
    category: "Airfare",
    receipt: "attached",
    policy: "inside",
    policyNote: "Fare class verified",
    source: "Email receipt",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-110",
    date: "May 21",
    submittedAt: "9:36 AM",
    member: "Rina Das",
    role: "CRG",
    initials: "RD",
    status: "details",
    amount: 58.94,
    merchant: "Lyft",
    memo: "Airport transfer",
    category: "Ground",
    receipt: "missing",
    policy: "needs-review",
    policyNote: "Receipt image unreadable",
    source: "Manual upload",
    reviewer: "Finance queue",
  },
  {
    id: "exp-111",
    date: "May 20",
    submittedAt: "6:05 PM",
    member: "Mateo Garcia",
    role: "Origination",
    initials: "MG",
    status: "payment",
    amount: 214.37,
    merchant: "Union Square Cafe",
    memo: "Investor intro dinner",
    category: "Meals",
    receipt: "attached",
    policy: "inside",
    policyNote: "Ready for payment run",
    source: "Mobile receipt",
    reviewer: "Jane Smith",
  },
  {
    id: "exp-112",
    date: "May 20",
    submittedAt: "1:14 PM",
    member: "Harper Klein",
    role: "TD Banking",
    initials: "HK",
    status: "pending",
    amount: 31.2,
    merchant: "MTA",
    memo: "Local client transit",
    category: "Transit",
    receipt: "not-required",
    policy: "inside",
    policyNote: "Under receipt threshold",
    source: "Corporate card sync",
    reviewer: "Jane Smith",
  },
];

export const statusMeta = {
  pending: { label: "Pending Review", tone: "amber" },
  payment: { label: "Payment Pending", tone: "blue" },
  declined: { label: "Declined", tone: "red" },
  details: { label: "Details Requested", tone: "purple" },
  action: { label: "Action Required", tone: "orange" },
  approved: { label: "Approved", tone: "green" },
};

export const filterTabs = [
  { id: "all", label: "All" },
  { id: "pending", label: "Pending Review" },
  { id: "needs-receipt", label: "Needs Receipt" },
  { id: "policy", label: "Policy Flags" },
];

export const categoryPalette = {
  Airfare: "sky",
  Ground: "mint",
  Lodging: "violet",
  Meals: "amber",
  Office: "slate",
  Software: "indigo",
  Transit: "green",
};
