export const dashboardData = {
  scopes: [
    { id: "week", label: "This week" },
    { id: "coverage", label: "My coverage" },
    { id: "team", label: "Team" },
  ],
  heroSignal: {
    sponsor: "Peak Rock Capital",
    title: "Sponsor appetite signal detected",
    status: "Needs confirmation",
    source: "Coverage note from John Kim",
    timestamp: "Today, 12:41 PM",
    confidence: 86,
    summary:
      "Coverage note indicates renewed interest in founder-owned healthcare services businesses under roughly $250M revenue, while avoiding HCIT this quarter.",
    excerpt:
      "Peak Rock continues to lean into fragmented Healthcare Services. They prefer founder-owned companies under ~$250M revenue and are avoiding HCIT this quarter. Geography may need confirmation before we refresh the screen.",
    criteria: [
      { label: "Sector focus", value: "Healthcare Services", state: "Explicit" },
      { label: "Ownership", value: "Founder-owned", state: "Explicit" },
      { label: "Revenue range", value: "Under ~$250M", state: "Explicit" },
      { label: "Exclude", value: "HCIT", state: "Explicit" },
      { label: "Geography", value: "North America", state: "Inferred" },
      { label: "Deal posture", value: "Control / add-on friendly", state: "Inferred" },
    ],
    validation: [
      {
        label: "Sponsor identified",
        state: "Passed",
        detail: "Peak Rock matched to active sponsor profile and sponsor coverage owner.",
      },
      {
        label: "Source grounded",
        state: "Passed",
        detail: "All explicit criteria appear in the coverage note excerpt.",
      },
      {
        label: "Prior rejection check",
        state: "Warning",
        detail: "Two HCIT ideas from last quarter should be suppressed before screening.",
      },
      {
        label: "Geography specified",
        state: "Warning",
        detail: "North America is inferred from historical coverage, not stated in source.",
      },
    ],
    agentSteps: [
      { label: "Detected", detail: "Coverage note indexed", tone: "teal" },
      { label: "Extracted", detail: "6 criteria drafted", tone: "teal" },
      { label: "Checked", detail: "2 warnings flagged", tone: "amber" },
      { label: "Paused", detail: "Human confirmation required", tone: "navy" },
    ],
    actions: [
      { id: "confirm", label: "Confirm criteria", style: "primary" },
      { id: "edit", label: "Edit criteria", style: "secondary" },
      { id: "coverage", label: "Ask coverage", style: "secondary" },
      { id: "dismiss", label: "Dismiss", style: "ghost" },
    ],
  },
  metrics: [
    {
      label: "Work requiring judgment",
      value: "37",
      trend: "+8 vs last week",
      tone: "amber",
      description: "Signals, reviews, intros, and stale assumptions waiting on a banker.",
    },
    {
      label: "Signals awaiting review",
      value: "14",
      trend: "6 high confidence",
      tone: "teal",
      description: "Relationship notes not yet committed to sponsor memory.",
    },
    {
      label: "Coverage reviews due",
      value: "7",
      trend: "3 due today",
      tone: "blue",
      description: "Idea books and packages waiting on internal coverage feedback.",
    },
    {
      label: "Relationship capital risks",
      value: "9",
      trend: "4 duplicates",
      tone: "red",
      description: "Prior rejection, stale source, or duplicate outreach risks.",
    },
  ],
  workGroups: [
    {
      id: "signals",
      label: "Signals",
      count: 14,
      items: [
        {
          id: "sig-peak-rock",
          title: "Peak Rock appetite signal",
          description: "Founder-owned healthcare services under ~$250M; HCIT excluded.",
          status: "Needs review",
          owner: "TD",
          sla: "Today",
          tone: "amber",
          score: 86,
          source: "Coverage note",
          next: "Confirm or edit criteria before sponsor memory is updated.",
          watch: "Geography is inferred; do not route externally before coverage confirmation.",
          detailMetric: "6 criteria",
        },
        {
          id: "sig-brightstar",
          title: "BrightStar succession signal",
          description: "Commercial banker heard founder may consider succession planning.",
          status: "Ask CB",
          owner: "CB",
          sla: "2d",
          tone: "teal",
          score: 78,
          source: "Banker note",
          next: "Ask the commercial banker to confirm founder openness.",
          watch: "Actionability is not confirmed; do not package for sponsor review yet.",
          detailMetric: "1 ambiguity",
        },
        {
          id: "sig-hcit",
          title: "HCIT avoidance signal",
          description: "Sponsor feedback conflicts with an existing HCIT idea-book theme.",
          status: "Suppress",
          owner: "Coverage",
          sla: "Now",
          tone: "red",
          score: 91,
          source: "Feedback email",
          next: "Suppress HCIT ideas for this sponsor until the next review window.",
          watch: "This is negative appetite signal, not a new idea.",
          detailMetric: "4 ideas",
        },
        {
          id: "sig-fund-close",
          title: "Business services fund-close signal",
          description: "Sponsor may be active after new fund close and dry powder update.",
          status: "Ready",
          owner: "TD",
          sla: "Fri",
          tone: "green",
          score: 82,
          source: "Public + CRM",
          next: "Draft criteria and run prior rejection checks.",
          watch: "Revenue and ownership bands are missing.",
          detailMetric: "12 sponsors",
        },
      ],
    },
    {
      id: "ideabooks",
      label: "Idea books",
      count: 41,
      items: [
        {
          id: "book-peak-rock",
          title: "Peak Rock provider services book",
          description: "14 curated ideas prepared from confirmed sponsor appetite.",
          status: "TD review",
          owner: "TD",
          sla: "Today",
          tone: "teal",
          score: 88,
          source: "Idea book",
          next: "Review evidence pack and select ideas for coverage meeting.",
          watch: "Two targets overlap with prior buyer-list discussion.",
          detailMetric: "14 ideas",
        },
        {
          id: "book-blackrock",
          title: "BlackRock tech-enabled services",
          description: "Sent to coverage; feedback pending from investor coverage.",
          status: "Sent",
          owner: "Coverage",
          sla: "3d",
          tone: "green",
          score: 76,
          source: "Coverage package",
          next: "Follow up and capture feedback as structured lifecycle data.",
          watch: "Avoid creating a second parallel package.",
          detailMetric: "9 ideas",
        },
        {
          id: "book-wellnex",
          title: "Wellnex care navigation revisit",
          description: "Held until sponsor appetite refresh and rejection reconciliation.",
          status: "Revisit",
          owner: "TD",
          sla: "2d",
          tone: "amber",
          score: 61,
          source: "Prior book",
          next: "Refresh appetite before sending to coverage.",
          watch: "Prior rejection reason is not yet mapped.",
          detailMetric: "5 stale",
        },
      ],
    },
    {
      id: "curated",
      label: "Curated ideas",
      count: 186,
      items: [
        {
          id: "idea-medbridge",
          title: "MedBridge for Peak Rock",
          description: "Recurring revenue healthcare services with operating partner intro path.",
          status: "High fit",
          owner: "TD",
          sla: "Today",
          tone: "green",
          score: 92,
          source: "Screen + graph",
          next: "Add to Peak Rock book and request coverage review.",
          watch: "Confirm introducer willingness before proposing outreach.",
          detailMetric: "92 fit",
        },
        {
          id: "idea-vitalscope",
          title: "Vitalscope actionability check",
          description: "Strong thesis fit, but commercial banker relationship is stale.",
          status: "Check",
          owner: "CB",
          sla: "1d",
          tone: "amber",
          score: 84,
          source: "C360 + notes",
          next: "Ask CB to confirm current management relationship.",
          watch: "Last meaningful interaction was 128 days ago.",
          detailMetric: "128d stale",
        },
        {
          id: "idea-cloudspan",
          title: "CloudSpan infrastructure software",
          description: "Pattern detected from prior buyer-list outcomes; evidence incomplete.",
          status: "Evidence",
          owner: "TD",
          sla: "Fri",
          tone: "blue",
          score: 73,
          source: "Prior outcomes",
          next: "Build evidence pack before sponsor scoring.",
          watch: "Source support is insufficient for external review.",
          detailMetric: "3 sources",
        },
      ],
    },
    {
      id: "prop",
      label: "Prop intros",
      count: 26,
      items: [
        {
          id: "prop-novamed",
          title: "Novamed proprietary intro",
          description: "High-priority exit angle with healthcare services sponsor fit.",
          status: "Active",
          owner: "TD",
          sla: "Today",
          tone: "teal",
          score: 81,
          source: "Prop intro",
          next: "Confirm sponsor fit and update actionability.",
          watch: "Do not duplicate outreach with coverage team.",
          detailMetric: "4 investors",
        },
        {
          id: "prop-flooring",
          title: "FlooringCo founder-owned intro",
          description: "Industrial services angle with warm commercial banker path.",
          status: "Qualify",
          owner: "CB",
          sla: "3d",
          tone: "amber",
          score: 69,
          source: "Referral",
          next: "Qualify founder openness before matching sponsors.",
          watch: "Sector tag conflicts with micro-sector mapping.",
          detailMetric: "2 gaps",
        },
      ],
    },
    {
      id: "coverage",
      label: "Coverage review",
      count: 7,
      items: [
        {
          id: "review-peak-rock",
          title: "Peak Rock coverage review package",
          description: "Seven selected ideas with evidence, criteria, and prior feedback.",
          status: "Ready",
          owner: "TD",
          sla: "Today",
          tone: "teal",
          score: 89,
          source: "Review package",
          next: "Send internally to sponsor coverage for review.",
          watch: "Package is internal only; no sponsor outreach yet.",
          detailMetric: "7 ideas",
        },
        {
          id: "review-forum",
          title: "Forum feedback capture",
          description: "Three coverage responses not yet logged as lifecycle feedback.",
          status: "Capture",
          owner: "TD",
          sla: "1d",
          tone: "amber",
          score: 64,
          source: "Email thread",
          next: "Extract feedback into structured reason and next-step fields.",
          watch: "Avoid losing rejection rationale in email history.",
          detailMetric: "3 replies",
        },
      ],
    },
    {
      id: "intros",
      label: "Proposed intros",
      count: 5,
      items: [
        {
          id: "intro-chen",
          title: "Dr. Emily Chen to Peak Rock",
          description: "Operating partner path to MedBridge; banker approval required.",
          status: "Approval",
          owner: "TD",
          sla: "Today",
          tone: "amber",
          score: 83,
          source: "Relationship graph",
          next: "Approve request only after the MedBridge idea is confirmed.",
          watch: "The agent should not request this intro automatically.",
          detailMetric: "Warm path",
        },
        {
          id: "intro-brightstar",
          title: "Commercial banker path to BrightStar",
          description: "CB owns relationship and can qualify founder openness.",
          status: "Info req.",
          owner: "CB",
          sla: "2d",
          tone: "teal",
          score: 77,
          source: "C360 graph",
          next: "Ask CB for actionability before adding to a sponsor book.",
          watch: "Founder openness remains unconfirmed.",
          detailMetric: "1 owner",
        },
      ],
    },
  ],
  lifecycle: [
    { label: "Signals detected", value: 42, helper: "14 need review", percent: 100, tone: "teal" },
    { label: "Criteria confirmed", value: 28, helper: "8 edited by TD", percent: 74, tone: "green" },
    { label: "Screens run", value: 31, helper: "12 flags removed", percent: 68, tone: "blue" },
    { label: "Sent to coverage", value: 16, helper: "7 feedback due", percent: 46, tone: "amber" },
    { label: "Converted / archived", value: 9, helper: "training data captured", percent: 28, tone: "navy" },
  ],
  appetiteMatrix: {
    sponsors: ["Peak Rock", "BlackRock", "Genstar", "KKR", "Arbor"],
    sectors: ["Healthcare Services", "Business Services", "Industrial Tech", "Software", "Financial Services"],
    cells: [
      [92, 66, 44, 38, 27],
      [58, 82, 71, 63, 42],
      [39, 74, 88, 31, 26],
      [46, 67, 72, 86, 55],
      [31, 52, 69, 48, 81],
    ],
  },
  feedbackHeatmap: [
    { label: "Good fit", values: [5, 7, 4, 9, 6, 8] },
    { label: "Too small", values: [2, 1, 4, 3, 2, 1] },
    { label: "Already shown", values: [4, 2, 1, 5, 3, 2] },
    { label: "Wrong timing", values: [3, 5, 2, 4, 6, 3] },
    { label: "Ask CB", values: [2, 4, 6, 3, 5, 7] },
  ],
  worklog: [
    {
      time: "12:43 PM",
      title: "Coverage note processed",
      detail: "Peak Rock appetite signal extracted and stored as draft criteria.",
      tone: "teal",
    },
    {
      time: "12:44 PM",
      title: "Duplicate check completed",
      detail: "Two HCIT ideas flagged for suppression due to current sponsor feedback.",
      tone: "amber",
    },
    {
      time: "12:46 PM",
      title: "Company screen prepared",
      detail: "142 healthcare services companies staged; not run until criteria confirmation.",
      tone: "blue",
    },
    {
      time: "12:48 PM",
      title: "Human checkpoint created",
      detail: "TD confirmation required before sponsor memory or screening workflow updates.",
      tone: "navy",
    },
  ],
  riskQueue: [
    {
      title: "Duplicate outreach risk",
      detail: "Two TD bankers are preparing asks on the same company relationship.",
      status: "Resolve now",
      tone: "red",
    },
    {
      title: "Stale sponsor appetite",
      detail: "Eight sponsor profiles conflict with recent coverage feedback.",
      status: "8 sponsors",
      tone: "amber",
    },
    {
      title: "Intro path not approved",
      detail: "Five warm paths exist, but banker approval is required before request.",
      status: "5 paths",
      tone: "teal",
    },
  ],
};
