name: Auto Deploy

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types: [requested]

permissions:
  contents: read
  deployments: write
  pages: write
  id-token: write
  actions: write

jobs:
  auto-approve-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve requested deploy run
        run: |
          gh api --method POST /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
